# Generated by Django 4.0.4 on 2022-11-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0002_mascota_dueño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='descriocion',
            new_name='descripcion',
        ),
    ]
